name: test
on: 
  workflow_dispatch:
    inputs: 
      greeting:
        type: string
        default: hello
        required: true
        description: A cheerful word
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "1"
          echo "${{inputs.greeting}}"
      - env:
          CONTEXT: ${{toJSON(github)}}  
        run: echo "${CONTEXT}"
                  
  test2:
    runs-on: ubuntu-latest
    steps: 
      - env:
          HOGE: ${{join('hi','test1')}}
        run: echo "${HOGE}"
        
  test3:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "${{join('hi','test2')}}"
        
