name: test
on: 
  workflow_dispatch:
    inputs: 
      greeting:
        type: string
        default: hello
        required: true
        description: A cheerful word
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "1"
         echo "${{inputs.greeting}}"
