name: test
on: 
  workflow_dispatch:
    inputs: 
      greeting:
        type: string
        default: hello
        required: true
        description: A cheerful word
jobs1:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "1"
         echo "${{inputs.greeting}}"
jpbs2:
  test2:
    runs-on: ubuntu-latest
    steps:
      -run:echo "$((github.actor))" 
