name: test
on: 
  workflow_dispatch:
    inputs: 
      greeting:
        type: string
        default: test_yymmdd
        required: true
        description: A cheerful word
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - env: 
          CONTEXT: ${{toJSON(github)}} 
        run: echo "${CONTEXT}"

  test1-2:
    runs-on: ubuntu-latest
    steps: 
      - env:
          HASH: ${{hashFiles('sandbox/.github/workflows/*.yml')}}
        run: echo "${HASH}"  
    
          
  test2:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "zengo check"
        if: ${{contain(github.run_id, '1')}}
        
  test3:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "${{join('hi','test2')}}"
