name: test
on: 
  workflow_dispatch:
    inputs: 
      greeting:
        type: string
        default: hello
        required: true
        description: A cheerful word
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - run: |
         echo "1"
         echo "${{inputs.greeting}}"
         
  test2:
    runs-on: ubuntu-latest
    steps: 
      - env:
          HOGE: ${{format('{0},{1}','hi','hoge')}}
        run: echo "${HOGE}"
        
  test3:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "${{format('{0},{1}','hi','hoge')}}"
        
