name: test
on: 
  workflow_dispatch:
    inputs: 
      greeting:
        type: string
        default: test_yymmdd
        required: true
        description: A cheerful word
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - env: 
          CONTEXT: ${{toJSON(github)}}  
          HASH: ${{hashFiles('.github/workflows/*.yml')}}
        run: |
          echo "${HASH}"
          echo "${CONTEXT}"               
  test2:
    runs-on: ubuntu-latest
    steps: 
      - env:
          HOGE: ${{join('hi','test1')}}
        run: echo "${HOGE}"
        
  test3:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "${{join('hi','test2')}}"
        
