name: test
on: 
  workflow_dispatch:
    inputs: 
      greeting:
        type: string
        default: test_yymmdd
        required: true
        description: A cheerful word
jobs:
  test1:
    runs-on: ubuntu-latest
    steps:
      - env: 
          CONTEXT: ${{toJSON(github)}} 
        run: echo "${CONTEXT}"

  test1-2:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${GITHUB_ACTOR}"
          echo "${GITHUB_HEAD_REF}"
          
  test2:
    runs-on: ubuntu-latest
    steps: 
      - run: echo "zengo check"
        if: ${{contains(github.run_id, '1')}}
        
  test3:
    runs-on: ubuntu-latest
    steps: 
      - id: source
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}"
      - env: 
          RESULT: ${{steps.source.output.result}}
        run: echo "${RESULT}"
